### ISSUE TITLE
Masonry layout becomes one column when navigating within the same template

### ISSUE THREAD

**Issue by melnychuk** [gmurphey/ember-masonry-grid#8]
We have a set of users and a bunch of cards for each user in Fixtures. Whenever you navigate from one user to another, the masonry becomes one column. Same thing happens whenever you make updates to the user model (even when modifying a property that's not related to the cards): the layout switches to a single column.

**Comment by gmurphey** [comment]
I'm guessing that this is due to the issue with #3. Masonry isn't recreating layouts when properties on `items` change, so your template within the component is being regenerated, and the DOM is losing all of the `style` attributes. I will work on getting a fix for this later tonight.

I'll also leave this issue open until I'm positive that #3 resolves it.

**Comment by mtennoe** [comment]
I am working with melnychuk on this. The fix solved the issue in some cases, but we can still see it occurring. Investigated this, I found that the reason seems to be that we use async links between our model objects, meaning that there is a short delay before all items are loaded from the fixture store. In the meanwhile, these model objects are considered as promises. This means that when masonry-grid does a imagesLoaded(), it does the recalculation of everything based on non-fulfilled promises, leading to one column. I have a suggested solution for this, where we add a check to see if the items-object is a promise or not. If it is a promise, we wait for fulfillment, if not we call imagesLoaded directly 

``` javascript
layoutMasonry: Ember.observer('items.@each', function () {
    var _this = this;

    if (this.items.then) {
        this.items.then(fulfill, reject);
    } else {
        fulfill();
    }

    function fulfill(answer) {
        imagesLoaded(_this.$(), function () {
          if (_this.get('masonryInitialized')) {
            _this.$().masonry('destroy');
          }

          _this.$().masonry(_this.get('options'));
          _this.set('masonryInitialized', true);
        });
    }

    function reject(reason) {
        console.log(reason);
    }
  })
```

If this is an acceptable solution for you, would you prefer a pull request?

**Comment by gmurphey** [comment]
Thanks for pursuing this further! I'll reopen this ticket and take a look at this a little later.

**Comment by gmurphey** [comment]
I wasn't able to get to this today. If you have a solution that works, feel free to send a pull request. Thanks!

**Comment by mtennoe** [comment]
Sure thing! Just sent a pull request for the proposed fix.
